basePath: /
definitions:
  dto.CreateDictRequest:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - description
    - name
    type: object
  dto.CreateTestRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  dto.CreateValueRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  dto.PutDictRequest:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - description
    - id
    - name
    type: object
  dto.PutTestRequest:
    properties:
      id:
        type: string
      name:
        type: string
    required:
    - id
    - name
    type: object
  dto.PutValueRequest:
    properties:
      id:
        type: string
      name:
        type: string
    required:
    - id
    - name
    type: object
info:
  contact: {}
  license: {}
  title: 后台
  version: latest
paths:
  /lt/api/v1:
    get:
      description: 获取平台版本
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取平台版本
      tags:
      - 获取平台版本
  /lt/api/v1/dict:
    post:
      consumes:
      - application/json
      description: 创建字典
      parameters:
      - description: 字典信息
        in: body
        name: CreateTestRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateDictRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 创建字典
      tags:
      - 字典
    put:
      consumes:
      - application/json
      description: 更新dict
      parameters:
      - description: dict信息
        in: body
        name: PutTestRequest
        required: true
        schema:
          $ref: '#/definitions/dto.PutDictRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 更新dict
      tags:
      - 字典
  /lt/api/v1/dict/{id}:
    delete:
      consumes:
      - application/json
      description: 删除dict
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 删除dict
      tags:
      - 字典
    get:
      consumes:
      - application/json
      description: 根据ID获取dict
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 根据ID获取dict
      tags:
      - 字典
  /lt/api/v1/test:
    post:
      consumes:
      - application/json
      description: 创建test
      parameters:
      - description: test信息
        in: body
        name: CreateTestRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 创建test
      tags:
      - test
    put:
      consumes:
      - application/json
      description: 更新test
      parameters:
      - description: test信息
        in: body
        name: PutTestRequest
        required: true
        schema:
          $ref: '#/definitions/dto.PutTestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 更新test
      tags:
      - test
  /lt/api/v1/test/{id}:
    delete:
      consumes:
      - application/json
      description: 删除test
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 删除test
      tags:
      - test
    get:
      consumes:
      - application/json
      description: 根据ID获取test
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 根据ID获取test
      tags:
      - test
  /lt/api/v1/value:
    post:
      consumes:
      - application/json
      description: 创建字典值
      parameters:
      - description: 字典值信息
        in: body
        name: CreateTestRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateValueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 创建字典值
      tags:
      - 字典
    put:
      consumes:
      - application/json
      description: 更新字典值
      parameters:
      - description: 字典值信息
        in: body
        name: PutTestRequest
        required: true
        schema:
          $ref: '#/definitions/dto.PutValueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 更新字典值
      tags:
      - 字典
  /lt/api/v1/value/{id}:
    delete:
      consumes:
      - application/json
      description: 删除字典值
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 删除d字典值
      tags:
      - 字典
    get:
      consumes:
      - application/json
      description: 根据ID获取dict值
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 根据ID获取dict值
      tags:
      - 字典
swagger: "2.0"
